name: theming_with_firebase_config
description: Server driven theming with firebase config

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.0
  firebase_core: ^1.12.0
  firebase_remote_config: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/profile.jpg
    - assets/images/midwife.png
